proto < ./../proto/library.proto
@host=http://localhost:50053

{{
    exports.token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJJRCI6MSwiTmFtZSI6IlJhbmR5IFN0ZXZlbiIsIkVtYWlsIjoicmFuZHlzdGV2ZW4xMkBnbWFpbC5jb20iLCJpc3MiOiJpc3N1ZXIiLCJleHAiOjE3MDIzNjc3NzN9.bSntE3Jnbto6ZuG-zloUE0Mso2-uX1QEJFq5isizoxA";
}}

####
GRPC /library.BookService/GetAllBooks
authorization: {{token}}
{}

####
GRPC /library.BookService/GetAllBooks
authorization: {{token}}
{}

####
GRPC /library.BookService/CreateBook
authorization: {{token}}
{
    "title": "",
    "description": "Buku terkuat di dunia dari gRPC",
    "quantity": 0,
    "cover": "Sampul",
    "authorId": 1
}