proto < ./../proto/library.proto
@host=http://localhost:50053

GRPC /library.BookService/GetAllBooks
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJJRCI6MSwiTmFtZSI6IlJhbmR5IFN0ZXZlbiIsIkVtYWlsIjoicmFuZHlzdGV2ZW4xMkBnbWFpbC5jb20iLCJpc3MiOiJpc3N1ZXIiLCJleHAiOjE3MDIzMTE1MDN9.j4wzZqU3_bqgj1PRKRQj3613fjOADeMMfpi_f-sxDoY
{}