proto < ./../proto/library.proto
@host=http://localhost:50053

####
GRPC /library.BookService/GetAllBooks
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJJRCI6MSwiTmFtZSI6IlJhbmR5IFN0ZXZlbiIsIkVtYWlsIjoicmFuZHlzdGV2ZW4xMkBnbWFpbC5jb20iLCJpc3MiOiJpc3N1ZXIiLCJleHAiOjE3MDIzNTQzOTB9.eRo1rfYzT1_XgrL1aTF9AwlNS2AeuhhuZJnCwPQW3kc
{}

####
GRPC /library.BookService/GetAllBooks
authorization: 
{}

####
GRPC /library.BookService/CreateBook
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJJRCI6MSwiTmFtZSI6IlJhbmR5IFN0ZXZlbiIsIkVtYWlsIjoicmFuZHlzdGV2ZW4xMkBnbWFpbC5jb20iLCJpc3MiOiJpc3N1ZXIiLCJleHAiOjE3MDIzNjczODd9.f8DBRrrb2LMD2Dq-wqRAFOAmq0_wfVJL3GyNqfxyBiE
{
    "title": "",
    "description": "Buku terkuat di dunia dari gRPC",
    "quantity": 0,
    "cover": "Sampul",
    "authorId": 1
}