proto < ./../proto/library.proto
@host=http://localhost:50053

####
GRPC /library.BorrowBookService/CreateBorrowBook
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJJRCI6MSwiTmFtZSI6IlJhbmR5IFN0ZXZlbiIsIkVtYWlsIjoicmFuZHlzdGV2ZW4xMkBnbWFpbC5jb20iLCJpc3MiOiJpc3N1ZXIiLCJleHAiOjE3MDIzNjUzMTl9.JjfdvTWfyiSQ2vnxWv1S323p1v1b6sn3aKC0vJAJ5Wc
{
    "bookId": 4
}
####
GRPC /library.BorrowBookService/RetrunBook
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJJRCI6MSwiTmFtZSI6IlJhbmR5IFN0ZXZlbiIsIkVtYWlsIjoicmFuZHlzdGV2ZW4xMkBnbWFpbC5jb20iLCJpc3MiOiJpc3N1ZXIiLCJleHAiOjE3MDIzNjUzMTl9.JjfdvTWfyiSQ2vnxWv1S323p1v1b6sn3aKC0vJAJ5Wc
{
    "borrowId": 19
}