proto < ./../proto/library.proto
@host=http://localhost:50053

{{
    exports.token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJJRCI6MSwiTmFtZSI6IlJhbmR5IFN0ZXZlbiIsIkVtYWlsIjoicmFuZHlzdGV2ZW4xMkBnbWFpbC5jb20iLCJpc3MiOiJpc3N1ZXIiLCJleHAiOjE3MDIzNzI5ODd9.dgDhP4U8mekheakHrpDOACOw0nuzC1SZV_qetQk_gak"
}}

####
GRPC /library.BorrowBookService/CreateBorrowBook
authorization: {{token}}
{
    "bookId": 2
}
####
GRPC /library.BorrowBookService/RetrunBook
authorization: {{token}}
{
    "borrowId": 22
}