// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	models "git.garena.com/sea-labs-id/bootcamp/batch-02/shared-projects/library-api/entity/models"
)

// AuthorRepository is an autogenerated mock type for the AuthorRepository type
type AuthorRepository struct {
	mock.Mock
}

// Find provides a mock function with given fields: ctx
func (_m *AuthorRepository) Find(ctx context.Context) ([]models.Author, error) {
	ret := _m.Called(ctx)

	var r0 []models.Author
	if rf, ok := ret.Get(0).(func(context.Context) []models.Author); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Author)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindAuthorByName provides a mock function with given fields: ctx, name
func (_m *AuthorRepository) FindAuthorByName(ctx context.Context, name string) (*models.Author, error) {
	ret := _m.Called(ctx, name)

	var r0 *models.Author
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.Author); ok {
		r0 = rf(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Author)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Save provides a mock function with given fields: ctx, author
func (_m *AuthorRepository) Save(ctx context.Context, author *models.Author) (*models.Author, error) {
	ret := _m.Called(ctx, author)

	var r0 *models.Author
	if rf, ok := ret.Get(0).(func(context.Context, *models.Author) *models.Author); ok {
		r0 = rf(ctx, author)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Author)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *models.Author) error); ok {
		r1 = rf(ctx, author)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewAuthorRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewAuthorRepository creates a new instance of AuthorRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewAuthorRepository(t mockConstructorTestingTNewAuthorRepository) *AuthorRepository {
	mock := &AuthorRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
