// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	models "git.garena.com/sea-labs-id/bootcamp/batch-02/shared-projects/library-api/entity/models"

	query "git.garena.com/sea-labs-id/bootcamp/batch-02/shared-projects/library-api/query"
)

// BookRepository is an autogenerated mock type for the BookRepository type
type BookRepository struct {
	mock.Mock
}

// Find provides a mock function with given fields: ctx, whereClause
func (_m *BookRepository) Find(ctx context.Context, whereClause []query.WhereClause) ([]models.Book, error) {
	ret := _m.Called(ctx, whereClause)

	var r0 []models.Book
	if rf, ok := ret.Get(0).(func(context.Context, []query.WhereClause) []models.Book); ok {
		r0 = rf(ctx, whereClause)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Book)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, []query.WhereClause) error); ok {
		r1 = rf(ctx, whereClause)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindBookByTitle provides a mock function with given fields: ctx, title
func (_m *BookRepository) FindBookByTitle(ctx context.Context, title string) (*models.Book, error) {
	ret := _m.Called(ctx, title)

	var r0 *models.Book
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.Book); ok {
		r0 = rf(ctx, title)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Book)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, title)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Save provides a mock function with given fields: ctx, book
func (_m *BookRepository) Save(ctx context.Context, book *models.Book) (*models.Book, error) {
	ret := _m.Called(ctx, book)

	var r0 *models.Book
	if rf, ok := ret.Get(0).(func(context.Context, *models.Book) *models.Book); ok {
		r0 = rf(ctx, book)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Book)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *models.Book) error); ok {
		r1 = rf(ctx, book)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewBookRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewBookRepository creates a new instance of BookRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewBookRepository(t mockConstructorTestingTNewBookRepository) *BookRepository {
	mock := &BookRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
