// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"

	mock "github.com/stretchr/testify/mock"
)

// BorrowHandler is an autogenerated mock type for the BorrowHandler type
type BorrowHandler struct {
	mock.Mock
}

// CreateBorrowRecord provides a mock function with given fields: c
func (_m *BorrowHandler) CreateBorrowRecord(c *gin.Context) {
	_m.Called(c)
}

// GetAllBorrowsRecord provides a mock function with given fields: c
func (_m *BorrowHandler) GetAllBorrowsRecord(c *gin.Context) {
	_m.Called(c)
}

// ReturnBorrowBook provides a mock function with given fields: c
func (_m *BorrowHandler) ReturnBorrowBook(c *gin.Context) {
	_m.Called(c)
}

type mockConstructorTestingTNewBorrowHandler interface {
	mock.TestingT
	Cleanup(func())
}

// NewBorrowHandler creates a new instance of BorrowHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewBorrowHandler(t mockConstructorTestingTNewBorrowHandler) *BorrowHandler {
	mock := &BorrowHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
