// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	models "git.garena.com/sea-labs-id/bootcamp/batch-02/shared-projects/library-api/entity/models"

	query "git.garena.com/sea-labs-id/bootcamp/batch-02/shared-projects/library-api/query"
)

// BorrowUseCase is an autogenerated mock type for the BorrowUseCase type
type BorrowUseCase struct {
	mock.Mock
}

// CreateBorrowRecord provides a mock function with given fields: ctx, borrow
func (_m *BorrowUseCase) CreateBorrowRecord(ctx context.Context, borrow *models.Borrow) (*models.Borrow, error) {
	ret := _m.Called(ctx, borrow)

	var r0 *models.Borrow
	if rf, ok := ret.Get(0).(func(context.Context, *models.Borrow) *models.Borrow); ok {
		r0 = rf(ctx, borrow)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Borrow)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *models.Borrow) error); ok {
		r1 = rf(ctx, borrow)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllBorrowsRecord provides a mock function with given fields: ctx, whereClauses
func (_m *BorrowUseCase) GetAllBorrowsRecord(ctx context.Context, whereClauses []query.WhereClause) ([]models.Borrow, error) {
	ret := _m.Called(ctx, whereClauses)

	var r0 []models.Borrow
	if rf, ok := ret.Get(0).(func(context.Context, []query.WhereClause) []models.Borrow); ok {
		r0 = rf(ctx, whereClauses)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Borrow)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, []query.WhereClause) error); ok {
		r1 = rf(ctx, whereClauses)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReturnBorrowedBookByBorrowId provides a mock function with given fields: ctx, borrowId, userId
func (_m *BorrowUseCase) ReturnBorrowedBookByBorrowId(ctx context.Context, borrowId uint, userId uint) (*models.Borrow, error) {
	ret := _m.Called(ctx, borrowId, userId)

	var r0 *models.Borrow
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint) *models.Borrow); ok {
		r0 = rf(ctx, borrowId, userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Borrow)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, uint, uint) error); ok {
		r1 = rf(ctx, borrowId, userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewBorrowUseCase interface {
	mock.TestingT
	Cleanup(func())
}

// NewBorrowUseCase creates a new instance of BorrowUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewBorrowUseCase(t mockConstructorTestingTNewBorrowUseCase) *BorrowUseCase {
	mock := &BorrowUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
