// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	models "git.garena.com/sea-labs-id/bootcamp/batch-02/shared-projects/library-api/entity/models"

	query "git.garena.com/sea-labs-id/bootcamp/batch-02/shared-projects/library-api/query"
)

// BorrowRepository is an autogenerated mock type for the BorrowRepository type
type BorrowRepository struct {
	mock.Mock
}

// Find provides a mock function with given fields: ctx, whereClauses
func (_m *BorrowRepository) Find(ctx context.Context, whereClauses []query.WhereClause) ([]models.Borrow, error) {
	ret := _m.Called(ctx, whereClauses)

	var r0 []models.Borrow
	if rf, ok := ret.Get(0).(func(context.Context, []query.WhereClause) []models.Borrow); ok {
		r0 = rf(ctx, whereClauses)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Borrow)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, []query.WhereClause) error); ok {
		r1 = rf(ctx, whereClauses)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindBorrowRecordById provides a mock function with given fields: ctx, id
func (_m *BorrowRepository) FindBorrowRecordById(ctx context.Context, id uint) (*models.Borrow, error) {
	ret := _m.Called(ctx, id)

	var r0 *models.Borrow
	if rf, ok := ret.Get(0).(func(context.Context, uint) *models.Borrow); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Borrow)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReturnBookByBorrowId provides a mock function with given fields: ctx, id
func (_m *BorrowRepository) ReturnBookByBorrowId(ctx context.Context, id uint) (*models.Borrow, error) {
	ret := _m.Called(ctx, id)

	var r0 *models.Borrow
	if rf, ok := ret.Get(0).(func(context.Context, uint) *models.Borrow); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Borrow)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Save provides a mock function with given fields: ctx, borrow
func (_m *BorrowRepository) Save(ctx context.Context, borrow *models.Borrow) (*models.Borrow, error) {
	ret := _m.Called(ctx, borrow)

	var r0 *models.Borrow
	if rf, ok := ret.Get(0).(func(context.Context, *models.Borrow) *models.Borrow); ok {
		r0 = rf(ctx, borrow)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Borrow)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *models.Borrow) error); ok {
		r1 = rf(ctx, borrow)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewBorrowRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewBorrowRepository creates a new instance of BorrowRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewBorrowRepository(t mockConstructorTestingTNewBorrowRepository) *BorrowRepository {
	mock := &BorrowRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
