// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/book.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BookRequest struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Quantity             uint32   `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Cover                string   `protobuf:"bytes,4,opt,name=cover,proto3" json:"cover,omitempty"`
	AuthorId             uint32   `protobuf:"varint,5,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BookRequest) Reset()         { *m = BookRequest{} }
func (m *BookRequest) String() string { return proto.CompactTextString(m) }
func (*BookRequest) ProtoMessage()    {}
func (*BookRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_eff6d7530e9d9699, []int{0}
}

func (m *BookRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BookRequest.Unmarshal(m, b)
}
func (m *BookRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BookRequest.Marshal(b, m, deterministic)
}
func (m *BookRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BookRequest.Merge(m, src)
}
func (m *BookRequest) XXX_Size() int {
	return xxx_messageInfo_BookRequest.Size(m)
}
func (m *BookRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BookRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BookRequest proto.InternalMessageInfo

func (m *BookRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *BookRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *BookRequest) GetQuantity() uint32 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

func (m *BookRequest) GetCover() string {
	if m != nil {
		return m.Cover
	}
	return ""
}

func (m *BookRequest) GetAuthorId() uint32 {
	if m != nil {
		return m.AuthorId
	}
	return 0
}

type BookResponses struct {
	Books                []*BookResponse `protobuf:"bytes,1,rep,name=books,proto3" json:"books,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *BookResponses) Reset()         { *m = BookResponses{} }
func (m *BookResponses) String() string { return proto.CompactTextString(m) }
func (*BookResponses) ProtoMessage()    {}
func (*BookResponses) Descriptor() ([]byte, []int) {
	return fileDescriptor_eff6d7530e9d9699, []int{1}
}

func (m *BookResponses) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BookResponses.Unmarshal(m, b)
}
func (m *BookResponses) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BookResponses.Marshal(b, m, deterministic)
}
func (m *BookResponses) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BookResponses.Merge(m, src)
}
func (m *BookResponses) XXX_Size() int {
	return xxx_messageInfo_BookResponses.Size(m)
}
func (m *BookResponses) XXX_DiscardUnknown() {
	xxx_messageInfo_BookResponses.DiscardUnknown(m)
}

var xxx_messageInfo_BookResponses proto.InternalMessageInfo

func (m *BookResponses) GetBooks() []*BookResponse {
	if m != nil {
		return m.Books
	}
	return nil
}

type BookResponse struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Quantity             uint32   `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Cover                string   `protobuf:"bytes,5,opt,name=cover,proto3" json:"cover,omitempty"`
	Author               *Author  `protobuf:"bytes,6,opt,name=author,proto3" json:"author,omitempty"`
	CreatedAt            string   `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt            string   `protobuf:"bytes,9,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BookResponse) Reset()         { *m = BookResponse{} }
func (m *BookResponse) String() string { return proto.CompactTextString(m) }
func (*BookResponse) ProtoMessage()    {}
func (*BookResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_eff6d7530e9d9699, []int{2}
}

func (m *BookResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BookResponse.Unmarshal(m, b)
}
func (m *BookResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BookResponse.Marshal(b, m, deterministic)
}
func (m *BookResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BookResponse.Merge(m, src)
}
func (m *BookResponse) XXX_Size() int {
	return xxx_messageInfo_BookResponse.Size(m)
}
func (m *BookResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BookResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BookResponse proto.InternalMessageInfo

func (m *BookResponse) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *BookResponse) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *BookResponse) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *BookResponse) GetQuantity() uint32 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

func (m *BookResponse) GetCover() string {
	if m != nil {
		return m.Cover
	}
	return ""
}

func (m *BookResponse) GetAuthor() *Author {
	if m != nil {
		return m.Author
	}
	return nil
}

func (m *BookResponse) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *BookResponse) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

func (m *BookResponse) GetDeletedAt() string {
	if m != nil {
		return m.DeletedAt
	}
	return ""
}

type Author struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CreatedAt            string   `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt            string   `protobuf:"bytes,5,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Author) Reset()         { *m = Author{} }
func (m *Author) String() string { return proto.CompactTextString(m) }
func (*Author) ProtoMessage()    {}
func (*Author) Descriptor() ([]byte, []int) {
	return fileDescriptor_eff6d7530e9d9699, []int{3}
}

func (m *Author) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Author.Unmarshal(m, b)
}
func (m *Author) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Author.Marshal(b, m, deterministic)
}
func (m *Author) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Author.Merge(m, src)
}
func (m *Author) XXX_Size() int {
	return xxx_messageInfo_Author.Size(m)
}
func (m *Author) XXX_DiscardUnknown() {
	xxx_messageInfo_Author.DiscardUnknown(m)
}

var xxx_messageInfo_Author proto.InternalMessageInfo

func (m *Author) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Author) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Author) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *Author) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

func (m *Author) GetDeletedAt() string {
	if m != nil {
		return m.DeletedAt
	}
	return ""
}

type SearchBook struct {
	Query                string   `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchBook) Reset()         { *m = SearchBook{} }
func (m *SearchBook) String() string { return proto.CompactTextString(m) }
func (*SearchBook) ProtoMessage()    {}
func (*SearchBook) Descriptor() ([]byte, []int) {
	return fileDescriptor_eff6d7530e9d9699, []int{4}
}

func (m *SearchBook) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchBook.Unmarshal(m, b)
}
func (m *SearchBook) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchBook.Marshal(b, m, deterministic)
}
func (m *SearchBook) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchBook.Merge(m, src)
}
func (m *SearchBook) XXX_Size() int {
	return xxx_messageInfo_SearchBook.Size(m)
}
func (m *SearchBook) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchBook.DiscardUnknown(m)
}

var xxx_messageInfo_SearchBook proto.InternalMessageInfo

func (m *SearchBook) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

func init() {
	proto.RegisterType((*BookRequest)(nil), "BookRequest")
	proto.RegisterType((*BookResponses)(nil), "BookResponses")
	proto.RegisterType((*BookResponse)(nil), "BookResponse")
	proto.RegisterType((*Author)(nil), "Author")
	proto.RegisterType((*SearchBook)(nil), "SearchBook")
}

func init() {
	proto.RegisterFile("proto/book.proto", fileDescriptor_eff6d7530e9d9699)
}

var fileDescriptor_eff6d7530e9d9699 = []byte{
	// 373 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x52, 0x4d, 0x6b, 0xe3, 0x30,
	0x10, 0xc5, 0x9f, 0x89, 0xc7, 0xf1, 0xb2, 0x88, 0x3d, 0x88, 0x2c, 0xcb, 0x1a, 0xf7, 0xe2, 0x5c,
	0x1c, 0x48, 0xfb, 0x07, 0x9c, 0x1e, 0x4a, 0xaf, 0xee, 0xad, 0x50, 0x82, 0x63, 0x09, 0x62, 0xe2,
	0x5a, 0x8e, 0x24, 0x17, 0xf2, 0x07, 0x0a, 0xbd, 0xf7, 0x07, 0x17, 0x4b, 0x4e, 0xe3, 0xa6, 0xd4,
	0x27, 0xfb, 0xbd, 0xa7, 0xd1, 0xbc, 0x37, 0x1a, 0xf8, 0xdd, 0x70, 0x26, 0xd9, 0x72, 0xcb, 0xd8,
	0x3e, 0x51, 0xbf, 0xd1, 0xbb, 0x01, 0xfe, 0x9a, 0xb1, 0x7d, 0x46, 0x0f, 0x2d, 0x15, 0x12, 0xfd,
	0x01, 0x47, 0x96, 0xb2, 0xa2, 0xd8, 0x08, 0x8d, 0xd8, 0xcb, 0x34, 0x40, 0x21, 0xf8, 0x84, 0x8a,
	0x82, 0x97, 0x8d, 0x2c, 0x59, 0x8d, 0x4d, 0xa5, 0x0d, 0x29, 0x34, 0x87, 0xe9, 0xa1, 0xcd, 0x6b,
	0x59, 0xca, 0x23, 0xb6, 0x42, 0x23, 0x0e, 0xb2, 0x4f, 0xdc, 0xdd, 0x59, 0xb0, 0x17, 0xca, 0xb1,
	0xad, 0xef, 0x54, 0x00, 0xfd, 0x05, 0x2f, 0x6f, 0xe5, 0x8e, 0xf1, 0x4d, 0x49, 0xb0, 0xa3, 0x4b,
	0x34, 0x71, 0x4f, 0xa2, 0x1b, 0x08, 0xb4, 0x2b, 0xd1, 0xb0, 0x5a, 0x50, 0x81, 0xae, 0xc0, 0xe9,
	0x5c, 0x0b, 0x6c, 0x84, 0x56, 0xec, 0xaf, 0x82, 0x64, 0x28, 0x67, 0x5a, 0x8b, 0x5e, 0x4d, 0x98,
	0x0d, 0x79, 0xf4, 0x0b, 0xcc, 0x92, 0xa8, 0x28, 0x41, 0x66, 0x96, 0xe4, 0x9c, 0xce, 0x1c, 0x49,
	0x67, 0x8d, 0xa7, 0xb3, 0x7f, 0x4a, 0xe7, 0x0c, 0xd3, 0xfd, 0x07, 0x57, 0x87, 0xc1, 0x6e, 0x68,
	0xc4, 0xfe, 0x6a, 0x92, 0xa4, 0x0a, 0x66, 0x3d, 0x8d, 0xfe, 0x01, 0x14, 0x9c, 0xe6, 0x92, 0x92,
	0x4d, 0x2e, 0xf1, 0x44, 0xd5, 0x7a, 0x3d, 0x93, 0xca, 0x4e, 0x6e, 0x1b, 0x72, 0x92, 0xa7, 0x5a,
	0xee, 0x19, 0x2d, 0x13, 0x5a, 0xd1, 0x5e, 0xf6, 0xb4, 0xdc, 0x33, 0xa9, 0x8c, 0xde, 0x0c, 0x70,
	0x75, 0xbf, 0x6f, 0x23, 0x40, 0x60, 0xd7, 0xf9, 0xf3, 0x69, 0x02, 0xea, 0xff, 0xc2, 0x8b, 0x35,
	0xee, 0xc5, 0x1e, 0xf7, 0xe2, 0x5c, 0x7a, 0x89, 0x00, 0x1e, 0x68, 0xce, 0x8b, 0x5d, 0xf7, 0x32,
	0xdd, 0xb4, 0x0e, 0x2d, 0xe5, 0xc7, 0xd3, 0x7e, 0x29, 0xb0, 0x7a, 0x02, 0xa7, 0x53, 0x05, 0x5a,
	0x00, 0xdc, 0xaa, 0xbe, 0xea, 0xf0, 0x2c, 0x19, 0xac, 0xe6, 0xfc, 0xeb, 0x9b, 0xa3, 0x05, 0xf8,
	0x77, 0x54, 0xa6, 0x55, 0xa5, 0x2b, 0xfd, 0xe4, 0xdc, 0xe5, 0xe2, 0xe8, 0xda, 0x7b, 0x9c, 0x24,
	0x4b, 0xb5, 0xef, 0x5b, 0x57, 0x7d, 0xae, 0x3f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x9d, 0xee, 0x57,
	0x6f, 0x0a, 0x03, 0x00, 0x00,
}
