// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/library.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserLoginRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserLoginRequest) Reset()         { *m = UserLoginRequest{} }
func (m *UserLoginRequest) String() string { return proto.CompactTextString(m) }
func (*UserLoginRequest) ProtoMessage()    {}
func (*UserLoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_594b252d607689b6, []int{0}
}

func (m *UserLoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserLoginRequest.Unmarshal(m, b)
}
func (m *UserLoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserLoginRequest.Marshal(b, m, deterministic)
}
func (m *UserLoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserLoginRequest.Merge(m, src)
}
func (m *UserLoginRequest) XXX_Size() int {
	return xxx_messageInfo_UserLoginRequest.Size(m)
}
func (m *UserLoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserLoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserLoginRequest proto.InternalMessageInfo

func (m *UserLoginRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserLoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type UserLoginResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Data                 string   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserLoginResponse) Reset()         { *m = UserLoginResponse{} }
func (m *UserLoginResponse) String() string { return proto.CompactTextString(m) }
func (*UserLoginResponse) ProtoMessage()    {}
func (*UserLoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_594b252d607689b6, []int{1}
}

func (m *UserLoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserLoginResponse.Unmarshal(m, b)
}
func (m *UserLoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserLoginResponse.Marshal(b, m, deterministic)
}
func (m *UserLoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserLoginResponse.Merge(m, src)
}
func (m *UserLoginResponse) XXX_Size() int {
	return xxx_messageInfo_UserLoginResponse.Size(m)
}
func (m *UserLoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserLoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserLoginResponse proto.InternalMessageInfo

func (m *UserLoginResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *UserLoginResponse) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type UserResponse struct {
	Id                   uint32               `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string               `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email                string               `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	PhoneNumber          string               `protobuf:"bytes,4,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Password             string               `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt            *timestamp.Timestamp `protobuf:"bytes,8,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *UserResponse) Reset()         { *m = UserResponse{} }
func (m *UserResponse) String() string { return proto.CompactTextString(m) }
func (*UserResponse) ProtoMessage()    {}
func (*UserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_594b252d607689b6, []int{2}
}

func (m *UserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserResponse.Unmarshal(m, b)
}
func (m *UserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserResponse.Marshal(b, m, deterministic)
}
func (m *UserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserResponse.Merge(m, src)
}
func (m *UserResponse) XXX_Size() int {
	return xxx_messageInfo_UserResponse.Size(m)
}
func (m *UserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserResponse proto.InternalMessageInfo

func (m *UserResponse) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UserResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UserResponse) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserResponse) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *UserResponse) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *UserResponse) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *UserResponse) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *UserResponse) GetDeletedAt() *timestamp.Timestamp {
	if m != nil {
		return m.DeletedAt
	}
	return nil
}

type ResponseGetUsers struct {
	Message              string          `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Users                []*UserResponse `protobuf:"bytes,2,rep,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ResponseGetUsers) Reset()         { *m = ResponseGetUsers{} }
func (m *ResponseGetUsers) String() string { return proto.CompactTextString(m) }
func (*ResponseGetUsers) ProtoMessage()    {}
func (*ResponseGetUsers) Descriptor() ([]byte, []int) {
	return fileDescriptor_594b252d607689b6, []int{3}
}

func (m *ResponseGetUsers) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseGetUsers.Unmarshal(m, b)
}
func (m *ResponseGetUsers) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseGetUsers.Marshal(b, m, deterministic)
}
func (m *ResponseGetUsers) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseGetUsers.Merge(m, src)
}
func (m *ResponseGetUsers) XXX_Size() int {
	return xxx_messageInfo_ResponseGetUsers.Size(m)
}
func (m *ResponseGetUsers) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseGetUsers.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseGetUsers proto.InternalMessageInfo

func (m *ResponseGetUsers) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *ResponseGetUsers) GetUsers() []*UserResponse {
	if m != nil {
		return m.Users
	}
	return nil
}

func init() {
	proto.RegisterType((*UserLoginRequest)(nil), "UserLoginRequest")
	proto.RegisterType((*UserLoginResponse)(nil), "UserLoginResponse")
	proto.RegisterType((*UserResponse)(nil), "UserResponse")
	proto.RegisterType((*ResponseGetUsers)(nil), "ResponseGetUsers")
}

func init() {
	proto.RegisterFile("proto/library.proto", fileDescriptor_594b252d607689b6)
}

var fileDescriptor_594b252d607689b6 = []byte{
	// 348 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0xcf, 0x4b, 0xfb, 0x30,
	0x18, 0xc6, 0x59, 0xb7, 0xee, 0xc7, 0xbb, 0xed, 0xcb, 0x96, 0xaf, 0x87, 0xd2, 0x8b, 0xb3, 0x5e,
	0x76, 0xca, 0x60, 0x82, 0xe0, 0xb1, 0x22, 0x78, 0x11, 0xc1, 0xa2, 0x17, 0x2f, 0x23, 0x33, 0xaf,
	0x5d, 0xa1, 0x6d, 0x6a, 0x92, 0x22, 0xfe, 0x67, 0xfe, 0x79, 0xd2, 0x34, 0x9d, 0x9d, 0x82, 0x3b,
	0x25, 0x4f, 0xde, 0xe7, 0xf3, 0x92, 0x3c, 0x79, 0xe1, 0x7f, 0x21, 0x85, 0x16, 0xab, 0x34, 0xd9,
	0x4a, 0x26, 0x3f, 0xa8, 0x51, 0xfe, 0x69, 0x2c, 0x44, 0x9c, 0xe2, 0xca, 0xa8, 0x6d, 0xf9, 0xba,
	0xd2, 0x49, 0x86, 0x4a, 0xb3, 0xac, 0xa8, 0x0d, 0xc1, 0x0d, 0xcc, 0x9e, 0x14, 0xca, 0x3b, 0x11,
	0x27, 0x79, 0x84, 0x6f, 0x25, 0x2a, 0x4d, 0x4e, 0xc0, 0xc5, 0x8c, 0x25, 0xa9, 0xd7, 0x59, 0x74,
	0x96, 0xa3, 0xa8, 0x16, 0xc4, 0x87, 0x61, 0xc1, 0x94, 0x7a, 0x17, 0x92, 0x7b, 0x8e, 0x29, 0xec,
	0x75, 0x10, 0xc2, 0xbc, 0xd5, 0x45, 0x15, 0x22, 0x57, 0x48, 0x3c, 0x18, 0x64, 0xa8, 0x14, 0x8b,
	0xd1, 0x36, 0x6a, 0x24, 0x21, 0xd0, 0xe3, 0x4c, 0x33, 0xdb, 0xc6, 0xec, 0x83, 0x4f, 0x07, 0x26,
	0x55, 0x8f, 0x3d, 0xfe, 0x0f, 0x9c, 0x84, 0x1b, 0x72, 0x1a, 0x39, 0x09, 0xaf, 0xa0, 0x9c, 0x65,
	0xd8, 0x40, 0xd5, 0xfe, 0xfb, 0xa6, 0xdd, 0xf6, 0x4d, 0xcf, 0x60, 0x52, 0xec, 0x44, 0x8e, 0x9b,
	0xbc, 0xcc, 0xb6, 0x28, 0xbd, 0x9e, 0x29, 0x8e, 0xcd, 0xd9, 0xbd, 0x39, 0x3a, 0x78, 0x8c, 0x7b,
	0xf8, 0x18, 0x72, 0x05, 0xf0, 0x22, 0x91, 0x69, 0xe4, 0x1b, 0xa6, 0xbd, 0xfe, 0xa2, 0xb3, 0x1c,
	0xaf, 0x7d, 0x5a, 0x07, 0x49, 0x9b, 0x20, 0xe9, 0x63, 0x13, 0x64, 0x34, 0xb2, 0xee, 0x50, 0x57,
	0x68, 0x59, 0xf0, 0x06, 0x1d, 0x1c, 0x47, 0xad, 0xbb, 0x46, 0x39, 0xa6, 0x68, 0xd1, 0xe1, 0x71,
	0xd4, 0xba, 0x43, 0x1d, 0x3c, 0xc0, 0xac, 0x49, 0xed, 0x16, 0x75, 0x15, 0xa2, 0xfa, 0x23, 0xfc,
	0x73, 0x70, 0xcb, 0xca, 0xe2, 0x39, 0x8b, 0xee, 0x72, 0xbc, 0x9e, 0xd2, 0x76, 0xea, 0x51, 0x5d,
	0x5b, 0x5f, 0x42, 0x2f, 0x2c, 0xf5, 0x8e, 0x50, 0x70, 0xcd, 0xa7, 0x92, 0x39, 0xfd, 0x39, 0x26,
	0x3e, 0xa1, 0xbf, 0xfe, 0xfc, 0x7a, 0xf4, 0x3c, 0xa0, 0x76, 0xd8, 0xfa, 0x66, 0xb9, 0xf8, 0x0a,
	0x00, 0x00, 0xff, 0xff, 0x2d, 0x11, 0xd0, 0x5c, 0x98, 0x02, 0x00, 0x00,
}
