// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/library_api.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BorrowRequest struct {
	BookId               uint32   `protobuf:"varint,1,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BorrowRequest) Reset()         { *m = BorrowRequest{} }
func (m *BorrowRequest) String() string { return proto.CompactTextString(m) }
func (*BorrowRequest) ProtoMessage()    {}
func (*BorrowRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6db4393e9fd1be97, []int{0}
}

func (m *BorrowRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BorrowRequest.Unmarshal(m, b)
}
func (m *BorrowRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BorrowRequest.Marshal(b, m, deterministic)
}
func (m *BorrowRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BorrowRequest.Merge(m, src)
}
func (m *BorrowRequest) XXX_Size() int {
	return xxx_messageInfo_BorrowRequest.Size(m)
}
func (m *BorrowRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BorrowRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BorrowRequest proto.InternalMessageInfo

func (m *BorrowRequest) GetBookId() uint32 {
	if m != nil {
		return m.BookId
	}
	return 0
}

type AuthRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthRequest) Reset()         { *m = AuthRequest{} }
func (m *AuthRequest) String() string { return proto.CompactTextString(m) }
func (*AuthRequest) ProtoMessage()    {}
func (*AuthRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6db4393e9fd1be97, []int{1}
}

func (m *AuthRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthRequest.Unmarshal(m, b)
}
func (m *AuthRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthRequest.Marshal(b, m, deterministic)
}
func (m *AuthRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthRequest.Merge(m, src)
}
func (m *AuthRequest) XXX_Size() int {
	return xxx_messageInfo_AuthRequest.Size(m)
}
func (m *AuthRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuthRequest proto.InternalMessageInfo

func (m *AuthRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *AuthRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type BorrowResponse struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	BorrowStatus         string   `protobuf:"bytes,2,opt,name=borrow_status,json=borrowStatus,proto3" json:"borrow_status,omitempty"`
	UserId               uint32   `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserName             string   `protobuf:"bytes,4,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	BookId               uint32   `protobuf:"varint,5,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	BookName             string   `protobuf:"bytes,6,opt,name=book_name,json=bookName,proto3" json:"book_name,omitempty"`
	BookQuantity         uint32   `protobuf:"varint,7,opt,name=book_quantity,json=bookQuantity,proto3" json:"book_quantity,omitempty"`
	CreatedAt            string   `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BorrowResponse) Reset()         { *m = BorrowResponse{} }
func (m *BorrowResponse) String() string { return proto.CompactTextString(m) }
func (*BorrowResponse) ProtoMessage()    {}
func (*BorrowResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6db4393e9fd1be97, []int{2}
}

func (m *BorrowResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BorrowResponse.Unmarshal(m, b)
}
func (m *BorrowResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BorrowResponse.Marshal(b, m, deterministic)
}
func (m *BorrowResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BorrowResponse.Merge(m, src)
}
func (m *BorrowResponse) XXX_Size() int {
	return xxx_messageInfo_BorrowResponse.Size(m)
}
func (m *BorrowResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BorrowResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BorrowResponse proto.InternalMessageInfo

func (m *BorrowResponse) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *BorrowResponse) GetBorrowStatus() string {
	if m != nil {
		return m.BorrowStatus
	}
	return ""
}

func (m *BorrowResponse) GetUserId() uint32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *BorrowResponse) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *BorrowResponse) GetBookId() uint32 {
	if m != nil {
		return m.BookId
	}
	return 0
}

func (m *BorrowResponse) GetBookName() string {
	if m != nil {
		return m.BookName
	}
	return ""
}

func (m *BorrowResponse) GetBookQuantity() uint32 {
	if m != nil {
		return m.BookQuantity
	}
	return 0
}

func (m *BorrowResponse) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *BorrowResponse) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

type AuthResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthResponse) Reset()         { *m = AuthResponse{} }
func (m *AuthResponse) String() string { return proto.CompactTextString(m) }
func (*AuthResponse) ProtoMessage()    {}
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6db4393e9fd1be97, []int{3}
}

func (m *AuthResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthResponse.Unmarshal(m, b)
}
func (m *AuthResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthResponse.Marshal(b, m, deterministic)
}
func (m *AuthResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthResponse.Merge(m, src)
}
func (m *AuthResponse) XXX_Size() int {
	return xxx_messageInfo_AuthResponse.Size(m)
}
func (m *AuthResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AuthResponse proto.InternalMessageInfo

func (m *AuthResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *AuthResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type BorrowBookResponse struct {
	Message              string          `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	BorrowResponse       *BorrowResponse `protobuf:"bytes,2,opt,name=borrow_response,json=borrowResponse,proto3" json:"borrow_response,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *BorrowBookResponse) Reset()         { *m = BorrowBookResponse{} }
func (m *BorrowBookResponse) String() string { return proto.CompactTextString(m) }
func (*BorrowBookResponse) ProtoMessage()    {}
func (*BorrowBookResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6db4393e9fd1be97, []int{4}
}

func (m *BorrowBookResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BorrowBookResponse.Unmarshal(m, b)
}
func (m *BorrowBookResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BorrowBookResponse.Marshal(b, m, deterministic)
}
func (m *BorrowBookResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BorrowBookResponse.Merge(m, src)
}
func (m *BorrowBookResponse) XXX_Size() int {
	return xxx_messageInfo_BorrowBookResponse.Size(m)
}
func (m *BorrowBookResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BorrowBookResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BorrowBookResponse proto.InternalMessageInfo

func (m *BorrowBookResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *BorrowBookResponse) GetBorrowResponse() *BorrowResponse {
	if m != nil {
		return m.BorrowResponse
	}
	return nil
}

func init() {
	proto.RegisterType((*BorrowRequest)(nil), "BorrowRequest")
	proto.RegisterType((*AuthRequest)(nil), "AuthRequest")
	proto.RegisterType((*BorrowResponse)(nil), "BorrowResponse")
	proto.RegisterType((*AuthResponse)(nil), "AuthResponse")
	proto.RegisterType((*BorrowBookResponse)(nil), "BorrowBookResponse")
}

func init() {
	proto.RegisterFile("proto/library_api.proto", fileDescriptor_6db4393e9fd1be97)
}

var fileDescriptor_6db4393e9fd1be97 = []byte{
	// 396 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0x4d, 0xaf, 0xd2, 0x40,
	0x14, 0xcd, 0xab, 0x8f, 0xf2, 0x7a, 0x5f, 0x5b, 0x74, 0x34, 0xa1, 0xc1, 0x98, 0x98, 0xea, 0x82,
	0x55, 0x49, 0x60, 0xa1, 0x2b, 0x0d, 0xb8, 0x22, 0x21, 0x26, 0x96, 0x9d, 0x9b, 0x66, 0x4a, 0x27,
	0x30, 0x29, 0xed, 0x94, 0x99, 0xa9, 0x84, 0xff, 0xe1, 0x0f, 0x36, 0xf3, 0x51, 0x28, 0x71, 0xf3,
	0x96, 0xe7, 0x9c, 0xfb, 0x71, 0xe6, 0xcc, 0x85, 0x71, 0xc3, 0x99, 0x64, 0xb3, 0x23, 0xcd, 0x39,
	0xe6, 0x97, 0x0c, 0x37, 0x34, 0xd1, 0x4c, 0x3c, 0x85, 0x60, 0xc5, 0x38, 0x67, 0xe7, 0x94, 0x9c,
	0x5a, 0x22, 0x24, 0x1a, 0xc3, 0x30, 0x67, 0xac, 0xcc, 0x68, 0x11, 0x3d, 0x7c, 0x7c, 0x98, 0x06,
	0xa9, 0xab, 0xe0, 0xba, 0x88, 0xbf, 0xc3, 0xf3, 0xb2, 0x95, 0x87, 0xae, 0xee, 0x1d, 0x0c, 0x48,
	0x85, 0xe9, 0x51, 0x57, 0x79, 0xa9, 0x01, 0x68, 0x02, 0x4f, 0x0d, 0x16, 0xe2, 0xcc, 0x78, 0x11,
	0x39, 0x5a, 0xb8, 0xe2, 0xf8, 0xaf, 0x03, 0x61, 0xb7, 0x4b, 0x34, 0xac, 0x16, 0x04, 0x85, 0xe0,
	0x5c, 0xf7, 0x38, 0xb4, 0x40, 0x9f, 0x20, 0xc8, 0x75, 0x45, 0x26, 0x24, 0x96, 0xad, 0xb0, 0x33,
	0x7c, 0x43, 0x6e, 0x35, 0xa7, 0x1c, 0xb6, 0x82, 0x70, 0xe5, 0xf0, 0x95, 0x71, 0xa8, 0xe0, 0xba,
	0x40, 0xef, 0xc1, 0xd3, 0x42, 0x8d, 0x2b, 0x12, 0x3d, 0x9a, 0xed, 0x8a, 0xf8, 0x89, 0x2b, 0xd2,
	0x7f, 0xd7, 0xa0, 0xff, 0x2e, 0xd5, 0xa5, 0x05, 0xdd, 0xe5, 0x9a, 0x2e, 0x45, 0xe8, 0x2e, 0x6d,
	0x88, 0x95, 0xd9, 0xa9, 0xc5, 0xb5, 0xa4, 0xf2, 0x12, 0x0d, 0x75, 0xaf, 0xaf, 0xc8, 0x5f, 0x96,
	0x43, 0x1f, 0x00, 0x76, 0x9c, 0x60, 0x49, 0x8a, 0x0c, 0xcb, 0xe8, 0x49, 0x8f, 0xf0, 0x2c, 0xb3,
	0x94, 0x4a, 0x6e, 0x9b, 0xa2, 0x93, 0x3d, 0x23, 0x5b, 0x66, 0x29, 0xe3, 0x6f, 0xe0, 0x9b, 0x5c,
	0x6d, 0x26, 0x11, 0x0c, 0x2b, 0x22, 0x04, 0xde, 0x13, 0x1b, 0x6d, 0x07, 0x55, 0xe4, 0x92, 0x95,
	0xa4, 0xb6, 0xa9, 0x18, 0x10, 0x1f, 0x00, 0x99, 0x54, 0x57, 0x8c, 0x95, 0x2f, 0x98, 0xf2, 0x15,
	0x46, 0x36, 0x63, 0x6e, 0x8b, 0xf5, 0xbc, 0xe7, 0xf9, 0x28, 0xb9, 0xff, 0x9d, 0x34, 0xcc, 0xef,
	0xf0, 0x7c, 0x03, 0x6f, 0x6e, 0x9b, 0xb6, 0x84, 0xff, 0xa1, 0x3b, 0x82, 0xbe, 0xc0, 0xeb, 0x1f,
	0xfa, 0xa9, 0x37, 0x09, 0x85, 0xc9, 0xdd, 0x4d, 0x4d, 0xde, 0x26, 0xff, 0x3b, 0x9c, 0x2f, 0xcc,
	0x3d, 0x75, 0x73, 0x3e, 0xc3, 0x60, 0xc3, 0xf6, 0xb4, 0x46, 0x7e, 0xd2, 0x3b, 0xb3, 0x49, 0x90,
	0xf4, 0xc3, 0x59, 0xb9, 0xbf, 0x1f, 0x93, 0x59, 0x93, 0xe7, 0xae, 0xbe, 0xde, 0xc5, 0xbf, 0x00,
	0x00, 0x00, 0xff, 0xff, 0xd8, 0xe7, 0x39, 0xaf, 0xd8, 0x02, 0x00, 0x00,
}
