// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: proto/library_api.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BorrowBookServiceClient is the client API for BorrowBookService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BorrowBookServiceClient interface {
	CreateBorrowBook(ctx context.Context, in *BorrowRequest, opts ...grpc.CallOption) (*BorrowBookResponse, error)
}

type borrowBookServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBorrowBookServiceClient(cc grpc.ClientConnInterface) BorrowBookServiceClient {
	return &borrowBookServiceClient{cc}
}

func (c *borrowBookServiceClient) CreateBorrowBook(ctx context.Context, in *BorrowRequest, opts ...grpc.CallOption) (*BorrowBookResponse, error) {
	out := new(BorrowBookResponse)
	err := c.cc.Invoke(ctx, "/BorrowBookService/CreateBorrowBook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BorrowBookServiceServer is the server API for BorrowBookService service.
// All implementations must embed UnimplementedBorrowBookServiceServer
// for forward compatibility
type BorrowBookServiceServer interface {
	CreateBorrowBook(context.Context, *BorrowRequest) (*BorrowBookResponse, error)
	mustEmbedUnimplementedBorrowBookServiceServer()
}

// UnimplementedBorrowBookServiceServer must be embedded to have forward compatible implementations.
type UnimplementedBorrowBookServiceServer struct {
}

func (UnimplementedBorrowBookServiceServer) CreateBorrowBook(context.Context, *BorrowRequest) (*BorrowBookResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateBorrowBook not implemented")
}
func (UnimplementedBorrowBookServiceServer) mustEmbedUnimplementedBorrowBookServiceServer() {}

// UnsafeBorrowBookServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BorrowBookServiceServer will
// result in compilation errors.
type UnsafeBorrowBookServiceServer interface {
	mustEmbedUnimplementedBorrowBookServiceServer()
}

func RegisterBorrowBookServiceServer(s grpc.ServiceRegistrar, srv BorrowBookServiceServer) {
	s.RegisterService(&BorrowBookService_ServiceDesc, srv)
}

func _BorrowBookService_CreateBorrowBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BorrowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BorrowBookServiceServer).CreateBorrowBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/BorrowBookService/CreateBorrowBook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BorrowBookServiceServer).CreateBorrowBook(ctx, req.(*BorrowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BorrowBookService_ServiceDesc is the grpc.ServiceDesc for BorrowBookService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BorrowBookService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "BorrowBookService",
	HandlerType: (*BorrowBookServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateBorrowBook",
			Handler:    _BorrowBookService_CreateBorrowBook_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/library_api.proto",
}

// AuthServiceClient is the client API for AuthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuthServiceClient interface {
	Login(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AuthResponse, error)
}

type authServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthServiceClient(cc grpc.ClientConnInterface) AuthServiceClient {
	return &authServiceClient{cc}
}

func (c *authServiceClient) Login(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AuthResponse, error) {
	out := new(AuthResponse)
	err := c.cc.Invoke(ctx, "/AuthService/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServiceServer is the server API for AuthService service.
// All implementations must embed UnimplementedAuthServiceServer
// for forward compatibility
type AuthServiceServer interface {
	Login(context.Context, *AuthRequest) (*AuthResponse, error)
	mustEmbedUnimplementedAuthServiceServer()
}

// UnimplementedAuthServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAuthServiceServer struct {
}

func (UnimplementedAuthServiceServer) Login(context.Context, *AuthRequest) (*AuthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedAuthServiceServer) mustEmbedUnimplementedAuthServiceServer() {}

// UnsafeAuthServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthServiceServer will
// result in compilation errors.
type UnsafeAuthServiceServer interface {
	mustEmbedUnimplementedAuthServiceServer()
}

func RegisterAuthServiceServer(s grpc.ServiceRegistrar, srv AuthServiceServer) {
	s.RegisterService(&AuthService_ServiceDesc, srv)
}

func _AuthService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/AuthService/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).Login(ctx, req.(*AuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AuthService_ServiceDesc is the grpc.ServiceDesc for AuthService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuthService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "AuthService",
	HandlerType: (*AuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _AuthService_Login_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/library_api.proto",
}
